config/routes.rb
Inventario::Application.routes.draw do
  namespace :admin do
    resources :returns
    resources :outputs
    resources :inputs
    resources :staffs
    resources :products
    resources :suppliers
    resources :units
    resources :catalogs
  end

end

app/models/admin/unit.rb
class Admin::Unit < ActiveRecord::Base
  attr_accessible :nom, :status, :symbol
end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < ApplicationController
  # GET /admin/units
  # GET /admin/units.json
  def index
    @admin_units = Admin::Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_units }
    end
  end

  # GET /admin/units/1
  # GET /admin/units/1.json
  def show
    @admin_unit = Admin::Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_unit }
    end
  end

  # GET /admin/units/new
  # GET /admin/units/new.json
  def new
    @admin_unit = Admin::Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_unit }
    end
  end

  # GET /admin/units/1/edit
  def edit
    @admin_unit = Admin::Unit.find(params[:id])
  end

  # POST /admin/units
  # POST /admin/units.json
  def create
    @admin_unit = Admin::Unit.new(params[:admin_unit])

    respond_to do |format|
      if @admin_unit.save
        format.html { redirect_to @admin_unit, notice: 'Unit was successfully created.' }
        format.json { render json: @admin_unit, status: :created, location: @admin_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/units/1
  # PUT /admin/units/1.json
  def update
    @admin_unit = Admin::Unit.find(params[:id])

    respond_to do |format|
      if @admin_unit.update_attributes(params[:admin_unit])
        format.html { redirect_to @admin_unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/units/1
  # DELETE /admin/units/1.json
  def destroy
    @admin_unit = Admin::Unit.find(params[:id])
    @admin_unit.destroy

    respond_to do |format|
      format.html { redirect_to admin_units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/units_helper.rb
module Admin::UnitsHelper
end

app/views/admin/units/_form.html.erb
<%= form_for(@admin_unit) do |f| %>
  <% if @admin_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_unit.errors.count, "error") %> prohibited this admin_unit from being saved:</h2>

      <ul>
      <% @admin_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/units/edit.html.erb
<h1>Editing admin_unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_unit %> |
<%= link_to 'Back', admin_units_path %>

app/views/admin/units/index.html.erb
<h1>Listing admin_units</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Symbol</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_units.each do |admin_unit| %>
  <tr>
    <td><%= admin_unit.nom %></td>
    <td><%= admin_unit.symbol %></td>
    <td><%= admin_unit.status %></td>
    <td><%= link_to 'Show', admin_unit %></td>
    <td><%= link_to 'Edit', edit_admin_unit_path(admin_unit) %></td>
    <td><%= link_to 'Destroy', admin_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_admin_unit_path %>

app/views/admin/units/new.html.erb
<h1>New admin_unit</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_units_path %>

app/views/admin/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @admin_unit.nom %>
</p>

<p>
  <b>Symbol:</b>
  <%= @admin_unit.symbol %>
</p>

<p>
  <b>Status:</b>
  <%= @admin_unit.status %>
</p>


<%= link_to 'Edit', edit_admin_unit_path(@admin_unit) %> |
<%= link_to 'Back', admin_units_path %>