config/routes.rb
Inventario::Application.routes.draw do
  namespace :admin do
    resources :returns
    resources :outputs
    resources :inputs
    resources :staffs
    resources :products
    resources :suppliers
    resources :units
    resources :catalogs
  end

end

app/models/admin/return.rb
class Admin::Return < ActiveRecord::Base
  belongs_to :catalog
  belongs_to :product
  belongs_to :unit
  belongs_to :staff
  attr_accessible :amount, :cod, :description, :state
end

app/controllers/admin/returns_controller.rb
class Admin::ReturnsController < ApplicationController
  # GET /admin/returns
  # GET /admin/returns.json
  def index
    @admin_returns = Admin::Return.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_returns }
    end
  end

  # GET /admin/returns/1
  # GET /admin/returns/1.json
  def show
    @admin_return = Admin::Return.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_return }
    end
  end

  # GET /admin/returns/new
  # GET /admin/returns/new.json
  def new
    @admin_return = Admin::Return.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_return }
    end
  end

  # GET /admin/returns/1/edit
  def edit
    @admin_return = Admin::Return.find(params[:id])
  end

  # POST /admin/returns
  # POST /admin/returns.json
  def create
    @admin_return = Admin::Return.new(params[:admin_return])

    respond_to do |format|
      if @admin_return.save
        format.html { redirect_to @admin_return, notice: 'Return was successfully created.' }
        format.json { render json: @admin_return, status: :created, location: @admin_return }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_return.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/returns/1
  # PUT /admin/returns/1.json
  def update
    @admin_return = Admin::Return.find(params[:id])

    respond_to do |format|
      if @admin_return.update_attributes(params[:admin_return])
        format.html { redirect_to @admin_return, notice: 'Return was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_return.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/returns/1
  # DELETE /admin/returns/1.json
  def destroy
    @admin_return = Admin::Return.find(params[:id])
    @admin_return.destroy

    respond_to do |format|
      format.html { redirect_to admin_returns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/returns_helper.rb
module Admin::ReturnsHelper
end

app/views/admin/returns/_form.html.erb
<%= form_for(@admin_return) do |f| %>
  <% if @admin_return.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_return.errors.count, "error") %> prohibited this admin_return from being saved:</h2>

      <ul>
      <% @admin_return.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod %><br />
    <%= f.text_field :cod %>
  </div>
  <div class="field">
    <%= f.label :catalog %><br />
    <%= f.text_field :catalog %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :staff %><br />
    <%= f.text_field :staff %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/returns/edit.html.erb
<h1>Editing admin_return</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_return %> |
<%= link_to 'Back', admin_returns_path %>

app/views/admin/returns/index.html.erb
<h1>Listing admin_returns</h1>

<table>
  <tr>
    <th>Cod</th>
    <th>Catalog</th>
    <th>Product</th>
    <th>Unit</th>
    <th>Staff</th>
    <th>State</th>
    <th>Amount</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_returns.each do |admin_return| %>
  <tr>
    <td><%= admin_return.cod %></td>
    <td><%= admin_return.catalog %></td>
    <td><%= admin_return.product %></td>
    <td><%= admin_return.unit %></td>
    <td><%= admin_return.staff %></td>
    <td><%= admin_return.state %></td>
    <td><%= admin_return.amount %></td>
    <td><%= admin_return.description %></td>
    <td><%= link_to 'Show', admin_return %></td>
    <td><%= link_to 'Edit', edit_admin_return_path(admin_return) %></td>
    <td><%= link_to 'Destroy', admin_return, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Return', new_admin_return_path %>

app/views/admin/returns/new.html.erb
<h1>New admin_return</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_returns_path %>

app/views/admin/returns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod:</b>
  <%= @admin_return.cod %>
</p>

<p>
  <b>Catalog:</b>
  <%= @admin_return.catalog %>
</p>

<p>
  <b>Product:</b>
  <%= @admin_return.product %>
</p>

<p>
  <b>Unit:</b>
  <%= @admin_return.unit %>
</p>

<p>
  <b>Staff:</b>
  <%= @admin_return.staff %>
</p>

<p>
  <b>State:</b>
  <%= @admin_return.state %>
</p>

<p>
  <b>Amount:</b>
  <%= @admin_return.amount %>
</p>

<p>
  <b>Description:</b>
  <%= @admin_return.description %>
</p>


<%= link_to 'Edit', edit_admin_return_path(@admin_return) %> |
<%= link_to 'Back', admin_returns_path %>