config/routes.rb
Inventario::Application.routes.draw do
  namespace :admin do
    resources :returns
    resources :outputs
    resources :inputs
    resources :staffs
    resources :products
    resources :suppliers
    resources :units
    resources :catalogs
  end

end

app/models/admin/product.rb
class Admin::Product < ActiveRecord::Base
  belongs_to :catalog
  belongs_to :unit
  belongs_to :supplier
  attr_accessible :amount, :description, :location, :manufacturer, :name, :price, :ref, :status
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Admin::Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_products }
    end
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
    @admin_product = Admin::Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/new
  # GET /admin/products/new.json
  def new
    @admin_product = Admin::Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Admin::Product.find(params[:id])
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Admin::Product.new(params[:admin_product])

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render json: @admin_product, status: :created, location: @admin_product }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  # PUT /admin/products/1.json
  def update
    @admin_product = Admin::Product.find(params[:id])

    respond_to do |format|
      if @admin_product.update_attributes(params[:admin_product])
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product = Admin::Product.find(params[:id])
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for(@admin_product) do |f| %>
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% @admin_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :catalog %><br />
    <%= f.text_field :catalog %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br />
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ref %><br />
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing admin_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing admin_products</h1>

<table>
  <tr>
    <th>Catalog</th>
    <th>Unit</th>
    <th>Supplier</th>
    <th>Name</th>
    <th>Ref</th>
    <th>Manufacturer</th>
    <th>Location</th>
    <th>Price</th>
    <th>Amount</th>
    <th>Status</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_products.each do |admin_product| %>
  <tr>
    <td><%= admin_product.catalog %></td>
    <td><%= admin_product.unit %></td>
    <td><%= admin_product.supplier %></td>
    <td><%= admin_product.name %></td>
    <td><%= admin_product.ref %></td>
    <td><%= admin_product.manufacturer %></td>
    <td><%= admin_product.location %></td>
    <td><%= admin_product.price %></td>
    <td><%= admin_product.amount %></td>
    <td><%= admin_product.status %></td>
    <td><%= admin_product.description %></td>
    <td><%= link_to 'Show', admin_product %></td>
    <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
    <td><%= link_to 'Destroy', admin_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New admin_product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Catalog:</b>
  <%= @admin_product.catalog %>
</p>

<p>
  <b>Unit:</b>
  <%= @admin_product.unit %>
</p>

<p>
  <b>Supplier:</b>
  <%= @admin_product.supplier %>
</p>

<p>
  <b>Name:</b>
  <%= @admin_product.name %>
</p>

<p>
  <b>Ref:</b>
  <%= @admin_product.ref %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @admin_product.manufacturer %>
</p>

<p>
  <b>Location:</b>
  <%= @admin_product.location %>
</p>

<p>
  <b>Price:</b>
  <%= @admin_product.price %>
</p>

<p>
  <b>Amount:</b>
  <%= @admin_product.amount %>
</p>

<p>
  <b>Status:</b>
  <%= @admin_product.status %>
</p>

<p>
  <b>Description:</b>
  <%= @admin_product.description %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>