config/routes.rb
Inventario::Application.routes.draw do
  namespace :admin do
    resources :returns
    resources :outputs
    resources :inputs
    resources :staffs
    resources :products
    resources :suppliers
    resources :units
    resources :catalogs
  end

end

app/models/admin/output.rb
class Admin::Output < ActiveRecord::Base
  belongs_to :catalog
  belongs_to :product
  belongs_to :unit
  belongs_to :staff
  attr_accessible :amount, :cod, :description
end

app/controllers/admin/outputs_controller.rb
class Admin::OutputsController < ApplicationController
  # GET /admin/outputs
  # GET /admin/outputs.json
  def index
    @admin_outputs = Admin::Output.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_outputs }
    end
  end

  # GET /admin/outputs/1
  # GET /admin/outputs/1.json
  def show
    @admin_output = Admin::Output.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_output }
    end
  end

  # GET /admin/outputs/new
  # GET /admin/outputs/new.json
  def new
    @admin_output = Admin::Output.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_output }
    end
  end

  # GET /admin/outputs/1/edit
  def edit
    @admin_output = Admin::Output.find(params[:id])
  end

  # POST /admin/outputs
  # POST /admin/outputs.json
  def create
    @admin_output = Admin::Output.new(params[:admin_output])

    respond_to do |format|
      if @admin_output.save
        format.html { redirect_to @admin_output, notice: 'Output was successfully created.' }
        format.json { render json: @admin_output, status: :created, location: @admin_output }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_output.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/outputs/1
  # PUT /admin/outputs/1.json
  def update
    @admin_output = Admin::Output.find(params[:id])

    respond_to do |format|
      if @admin_output.update_attributes(params[:admin_output])
        format.html { redirect_to @admin_output, notice: 'Output was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_output.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/outputs/1
  # DELETE /admin/outputs/1.json
  def destroy
    @admin_output = Admin::Output.find(params[:id])
    @admin_output.destroy

    respond_to do |format|
      format.html { redirect_to admin_outputs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/outputs_helper.rb
module Admin::OutputsHelper
end

app/views/admin/outputs/_form.html.erb
<%= form_for(@admin_output) do |f| %>
  <% if @admin_output.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_output.errors.count, "error") %> prohibited this admin_output from being saved:</h2>

      <ul>
      <% @admin_output.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod %><br />
    <%= f.text_field :cod %>
  </div>
  <div class="field">
    <%= f.label :catalog %><br />
    <%= f.text_field :catalog %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :staff %><br />
    <%= f.text_field :staff %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/outputs/edit.html.erb
<h1>Editing admin_output</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_output %> |
<%= link_to 'Back', admin_outputs_path %>

app/views/admin/outputs/index.html.erb
<h1>Listing admin_outputs</h1>

<table>
  <tr>
    <th>Cod</th>
    <th>Catalog</th>
    <th>Product</th>
    <th>Unit</th>
    <th>Amount</th>
    <th>Staff</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_outputs.each do |admin_output| %>
  <tr>
    <td><%= admin_output.cod %></td>
    <td><%= admin_output.catalog %></td>
    <td><%= admin_output.product %></td>
    <td><%= admin_output.unit %></td>
    <td><%= admin_output.amount %></td>
    <td><%= admin_output.staff %></td>
    <td><%= admin_output.description %></td>
    <td><%= link_to 'Show', admin_output %></td>
    <td><%= link_to 'Edit', edit_admin_output_path(admin_output) %></td>
    <td><%= link_to 'Destroy', admin_output, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Output', new_admin_output_path %>

app/views/admin/outputs/new.html.erb
<h1>New admin_output</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_outputs_path %>

app/views/admin/outputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod:</b>
  <%= @admin_output.cod %>
</p>

<p>
  <b>Catalog:</b>
  <%= @admin_output.catalog %>
</p>

<p>
  <b>Product:</b>
  <%= @admin_output.product %>
</p>

<p>
  <b>Unit:</b>
  <%= @admin_output.unit %>
</p>

<p>
  <b>Amount:</b>
  <%= @admin_output.amount %>
</p>

<p>
  <b>Staff:</b>
  <%= @admin_output.staff %>
</p>

<p>
  <b>Description:</b>
  <%= @admin_output.description %>
</p>


<%= link_to 'Edit', edit_admin_output_path(@admin_output) %> |
<%= link_to 'Back', admin_outputs_path %>